---
title: "Biomass_regeneration"
author: ""
date: "16 August 2018"
output: pdf_document
---

# Overview

Biomass_regeneration is a SpaDES module that simulates post-disturbance regeneration mechanisms for LBMR. As such, this module is mostly based of the post-disturbance regeneration mechanisms present in LANDIS-II Biomass Succession v3.2.1 extension (see see [LANDIS-II Biomass Succession v3.2 User Guide](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/blob/master/docs/LANDIS-II%20Biomass%20Succession%20v3.2%20User%20Guide.docx) and [Scheller and Mladenoff (2004)](https://pdfs.semanticscholar.org/4d38/d0be6b292eccd444af399775d37a757d1967.pdf). At the moment, the Biomass_regeneration module only simulates post-fire disturbance effects on forest species, by simualting post-fire mortality and activating resprouting and seeding mechanisms for each species, depending on their traits (i.e. ability to resprout and/or germinate from seeds following fire). Post-fire mortality behaves in a stand-replacing fashion, i.e. should a pixel be within a fire perimeter (determined by a fire raster) all cohorts see their biomasses set to 0.
As for post-fire regeneration, the module first evaluates whether any species present prior to fire were capable of post-fire seeding germination. If so, these species will germinate depending on light conditions and their shade tolerance, and depending on their establishment probability (i.e. germination success) in that pixel. The module then evaluates if any species present before fire are capable of resprouting 



## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
library(SpaDES)

setPaths(modulePath = file.path("E:/GitHub/LandscapesInMotion/R/SpaDES/m"))
getPaths() # shows where the 4 relevant paths are

times <- list(start = 0, end = 10)

parameters <- list(
  #.progress = list(type = "text", interval = 1), # for a progress bar
  ## If there are further modules, each can have its own set of parameters:
  #module1 = list(param1 = value1, param2 = value2),
  #module2 = list(param1 = value1, param2 = value2)
)
modules <- list("Biomass_regeneration")
objects <- list()
inputs <- list()
outputs <- list()

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects)

mySimOut <- spades(mySim)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("Biomass_regeneration", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

